config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :directors do
    collection do
      get "search"
    end
  end

  resources :actors do
    collection do
      get "search"
    end
  end

  resources :genres do
    collection do
      get "search"
    end
  end

  resources :movies do
    collection do
      get "search"
    end
  end
  root "movies#index"
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movies, through: :genre_movies
  has_and_belongs_to_many :movies

  validates :name, presence: true, uniqueness: true
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    # binding.pry
    @genre = Genre.new(genre_params)
    
    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: "Жанр был успешно создан." }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: "Жанр был успешно обновлён." }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: "Жанр был успешно удалён." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> попрепятствовало сохранению фильма:</h2>

      <ul>
      <% genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, for: :name%>
    <%= form.text_field :name, id: :name, class: 'form-control' %>
  </div>

  <%= form.submit class: "btn btn-info"%>

<% end %>

app/views/genres/edit.html.erb
<h1>Редактирование жанра</h1>

<div class="row">
	<div class="col-md-4">
		<%= render 'form', genre: @genre %>
	</div>
</div>
<%= link_to 'Инфо', @genre %> |
<%= link_to 'Назад', genres_path %> |
<%= link_to 'Удалить', @genre, method: :delete, data: { confirm: 'Вы уверены?' } %>

app/views/genres/index.html.erb
<div class="row">
  <% @genres.each do |genre| %>
    <div class="col-sm-6 col-md-2 genre-tile">
        <div class="row genre-prev-data">
          <div class="name col-7" title="<%= genre.name %>">
            <%= genre.name %>
          </div>
        </div>
        <hr/>
    </div>
  <% end %>
</div>

app/views/genres/new.html.erb
<h1>Новый жанр</h1>

<div class="row">
	<div class="col-md-4">
		<%= render 'form', genre: @genre %>
	</div>
</div>

<%= link_to 'Назад', genres_path %>

app/views/genres/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= @genre.name %></h1>
  </div>
  <div class="col-md-offset-5">
    <%= link_to 'Изменить', edit_genre_path(@genre) %> |
    <%= link_to 'Назад', genres_path %>
  </div>
</div> 
<div class="row">
  <div class="col genre-data">
    <p>
      <strong>Название:</strong>
      <%= @genre.name %>
    </p>
  </div>
</div>