config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :directors do
    collection do
      get "search"
    end
  end

  resources :actors do
    collection do
      get "search"
    end
  end

  resources :genres do
    collection do
      get "search"
    end
  end

  resources :movies do
    collection do
      get "search"
    end
  end
  root "movies#index"
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_attached_file :photo, styles: { medium: "400x600#", thumb: "150x250#" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  has_many :movies, through: :actor_movies
  has_and_belongs_to_many :movies

  validates :name, presence: true
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: "Актёр был успешно создан." }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: "Актёр был успешно обновлён." }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: "Актёр был успешно удалён." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name, :second_name, :third_name, :photo)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/views/actors/_form.html.erb
<% content_for :styles do %>
  <%= stylesheet_link_tag 'actors' %>
<% end %>

<% content_for :javascripts do %>
  <%= javascript_include_tag 'photo_preview' %>
<% end %>

<%= form_with(model: actor, html: { multipart: true }) do |form| %>
  <% if actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actor.errors.count, "error") %> попрепятствовало сохранению актёра:</h2>

      <ul>
      <% actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, for: :name%>
    <%= form.text_field :name, id: :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :second_name, for: :second_name %>
    <%= form.text_field :second_name, id: :second_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :third_name, for: :third_name %>
    <%= form.text_field :third_name, id: :third_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :photo, for: :photo %>
    <%= form.file_field :photo, id: :image_field%>
  </div>

  <%= form.submit class: "btn btn-info"%>

<% end %>

app/views/actors/edit.html.erb
<h1>Редактирование актёра</h1>

<div class="row">
	<div class="col-md-4">
		<%= render 'form', actor: @actor %>
	</div>
	<div class="col" id="image-prev">
		<%= image_tag @actor.photo.url(:medium), class: "image-big"%>
	</div>
</div>
<%= link_to 'Инфо', @actor %> |
<%= link_to 'Назад', actors_path %> |
<%= link_to 'Удалить', @actor, method: :delete, data: { confirm: 'Вы уверены?' } %>

app/views/actors/index.html.erb
<div class="row">
  <% @actors.each do |actor| %>
    <div class="col-sm-6 col-md-2 actor-tile">
        <div class="thumbnail">
          <%= link_to (image_tag actor.photo.url(:thumb), class: 'image', alt: actor.name+" "+actor.second_name, title: actor.name+" "+actor.second_name), actor%>
        </div>
        <div class="row actor-prev-data">
          <div class="name col-7" title="<%= actor.name %>">
            <%= actor.name %>
          </div>
          <div class="second_name col-7" title="<%= actor.second_name %>">
            <%= actor.second_name %>
          </div>
          <div class="third_name col-7" title="<%= actor.third_name %>">
            <%= actor.third_name %>
          </div>
        </div>
        <hr/>
    </div>
  <% end %>
</div>

app/views/actors/new.html.erb
<h1>Новый актёр</h1>

<div class="row">
	<div class="col-md-4">
		<%= render 'form', actor: @actor %>
	</div>
	<div class="col" id="image-prev">
	</div>
</div>

<%= link_to 'Назад', actors_path %>

app/views/actors/show.html.erb
<% content_for :styles do %>
  <%= stylesheet_link_tag 'actors' %>
<% end %>

<div class="row">
  <div class="col-md-6">
    <h1><%= @actor.name+" "+@actor.second_name %></h1>
  </div>
  <div class="col-md-offset-5">
    <%= link_to 'Изменить', edit_actor_path(@actor) %> |
    <%= link_to 'Назад', actors_path %>
  </div>
</div> 
<div class="row">
  <div class="col-md-4 image-frame">
    <%= image_tag @actor.photo.url(:medium), class: "image-big"%>
  </div>
  <div class="col actor-data">
    <p>
      <strong>Имя:</strong>
      <%= @actor.name %>
    </p>
    <p>
      <strong>Фамилия:</strong>
      <%= @actor.second_name %>
    </p>
    <p>
      <strong>Отчество:</strong>
      <%= @actor.third_name %>
    </p>
  </div>
</div>