config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :directors do
    collection do
      get "search"
    end
  end

  resources :actors do
    collection do
      get "search"
    end
  end

  resources :genres do
    collection do
      get "search"
    end
  end

  resources :movies do
    collection do
      get "search"
    end
  end
  root "movies#index"
end

app/models/director.rb
class Director < ApplicationRecord
  has_attached_file :photo, styles: { medium: "400x600#", thumb: "150x250#" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  has_many :movies, as: :collectable

  validates :name, presence: true
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :update, :destroy]

  # GET /directors
  # GET /directors.json
  def index
    @directors = Director.all
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
  end

  # GET /directors/new
  def new
    @director = Director.new
  end

  # GET /directors/1/edit
  def edit
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: "Режиссёр был успешно создан." }
        format.json { render :show, status: :created, location: @director }
      else
        format.html { render :new }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directors/1
  # PATCH/PUT /directors/1.json
  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to @director, notice: "Режиссёр был успешно обновлён." }
        format.json { render :show, status: :ok, location: @director }
      else
        format.html { render :edit }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director.destroy
    respond_to do |format|
      format.html { redirect_to directors_url, notice: "Режиссёр был успешно удалён." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_director
      @director = Director.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def director_params
      params.require(:director).permit(:name, :second_name, :third_name, :photo)
    end
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/views/directors/_form.html.erb
<% content_for :styles do %>
  <%= stylesheet_link_tag 'directors' %>
<% end %>

<% content_for :javascripts do %>
  <%= javascript_include_tag 'photo_preview' %>
<% end %>

<%= form_with(model: director, html: { multipart: true }) do |form| %>
  <% if director.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(director.errors.count, "error") %> попрепятствовало сохранению режиссёра:</h2>

      <ul>
      <% director.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, for: :name%>
    <%= form.text_field :name, id: :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :second_name, for: :second_name %>
    <%= form.text_field :second_name, id: :second_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :third_name, for: :third_name %>
    <%= form.text_field :third_name, id: :third_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :photo, for: :photo %>
    <%= form.file_field :photo, id: :image_field %>
  </div>

  <%= form.submit class: "btn btn-info"%>

<% end %>

app/views/directors/edit.html.erb
<h1>Редактирование режиссёра</h1>

<div class="row">
	<div class="col-md-4">
		<%= render 'form', director: @director %>
	</div>
	<div class="col" id="image-prev">
		<%= image_tag @director.photo.url(:medium), class: "image-big"%>
	</div>
</div>
<%= link_to 'Инфо', @director %> |
<%= link_to 'Назад', directors_path %> |
<%= link_to 'Удалить', @director, method: :delete, data: { confirm: 'Вы уверены?' } %>

app/views/directors/index.html.erb
<div class="row">
  <% @directors.each do |director| %>
    <div class="col-sm-6 col-md-2 director-tile">
        <div class="thumbnail">
          <%= link_to (image_tag director.photo.url(:thumb), class: 'image', alt: director.name+" "+director.second_name, title: director.name+" "+director.second_name), director%>
        </div>
        <div class="row director-prev-data">
          <div class="name col-7" title="<%= director.name %>">
            <%= director.name %>
          </div>
          <div class="second_name col-7" title="<%= director.second_name %>">
            <%= director.second_name %>
          </div>
          <div class="third_name col-7" title="<%= director.third_name %>">
            <%= director.third_name %>
          </div>
        </div>
        <hr/>
    </div>
  <% end %>
</div>

app/views/directors/new.html.erb
<h1>Новый режиссёр</h1>

<div class="row">
	<div class="col-md-4">
		<%= render 'form', director: @director %>
	</div>
	<div class="col" id="image-prev">
	</div>
</div>

<%= link_to 'Назад', directors_path %>

app/views/directors/show.html.erb
<% content_for :styles do %>
  <%= stylesheet_link_tag 'directors' %>
<% end %>

<div class="row">
  <div class="col-md-6">
    <h1><%= @director.name+" "+@director.second_name %></h1>
  </div>
  <div class="col-md-offset-5">
    <%= link_to 'Изменить', edit_director_path(@director) %> |
    <%= link_to 'Назад', directors_path %>
  </div>
</div> 
<div class="row">
  <div class="col-md-4 image-frame">
    <%= image_tag @director.photo.url(:medium), class: "image-big"%>
  </div>
  <div class="col director-data">
    <p>
      <strong>Имя:</strong>
      <%= @director.name %>
    </p>
    <p>
      <strong>Фамилия:</strong>
      <%= @director.second_name %>
    </p>
    <p>
      <strong>Отчество:</strong>
      <%= @director.third_name %>
    </p>
  </div>
</div>