config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :directors do
    collection do
      get "search"
    end
  end

  resources :actors do
    collection do
      get "search"
    end
  end

  resources :genres do
    collection do
      get "search"
    end
  end

  resources :movies do
    collection do
      get "search"
    end
  end
  root "movies#index"
end

app/views/layouts/_header.html.erb
<header class="main-header">
    <%= link_to "Обзоры", root_path, class: "navbar-brand" %>

    <nav class="navbar navbar-static-top" role="navigation">

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li>
                <form class="form-inline pull-xs-right">
                    <input class="form-control" type="text" placeholder="Поиск">
                    <button class="btn btn-success-outline" type="submit">Поиск</button>
                </form>
                </li>
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/_sidebar.html.erb
<nav class="navbar bg-inverse navbar-fixed-left">
  <ul class="nav navbar-nav">
    <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to("Добавить фильм", new_movie_url, method: :get, class: 'nav-link')%>
      </li>
      <li class="nav-item">
        <%= link_to("Добавить актёра", new_actor_url, method: :get, class: 'nav-link')%>
      </li>
      <li class="nav-item">
        <%= link_to("Добавить режиссёра", new_director_url, method: :get, class: 'nav-link')%>
      </li>

      <li class="nav-item">
        <%= link_to("Добавить жанр", new_genre_url, method: :get, class: 'nav-link')%>
      </li>
      <li class="nav-item">
        <%= link_to("Выйти", destroy_user_session_url, method: :delete, class: 'nav-link') %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to("Войти", new_user_session_url, method: :get, class: 'nav-link') %>
      </li>
      <li class="nav-item">
        <%= link_to("Регистрация", new_user_registration_url, method: :get, class: 'nav-link') %>
      </li>
    <% end %>
    <li class="nav-item">
      <%= link_to("О сайте", root_url, method: :get, class: 'nav-link') %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Нетленочки</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield :styles%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :javascripts%>
  </head>

  <body>
  <div class="site-container">	
    <%= render 'layouts/header' %>
    <%= render 'layouts/sidebar' %>
    <div class="main-container">
        <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert alert-success") %>
        <% end %>
        <%= yield %>
    </div>
  </div>		    
  </body>
</html>